RunnerDiary/Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RunnerDiary.Models;

namespace RunnerDiary.Controllers
{
    public class DiaryController : Controller
    {
        private DiaryDBContext db = new DiaryDBContext();

        //
        // GET: /Diary/

        public ActionResult Index()
        {
            return View(db.RunDiary.ToList());
        }

        //
        // GET: /Diary/Details/5

        public ActionResult Details(int id = 0)
        {
            DailyEntry dailyentry = db.RunDiary.Find(id);
            if (dailyentry == null)
            {
                return HttpNotFound();
            }
            return View(dailyentry);
        }

        //
        // GET: /Diary/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Diary/Create

        [HttpPost]
        public ActionResult Create(DailyEntry dailyentry)
        {
            if (ModelState.IsValid)
            {
                db.RunDiary.Add(dailyentry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dailyentry);
        }

        //
        // GET: /Diary/Edit/5

        public ActionResult Edit(int id = 0)
        {
            DailyEntry dailyentry = db.RunDiary.Find(id);
            if (dailyentry == null)
            {
                return HttpNotFound();
            }
            return View(dailyentry);
        }

        //
        // POST: /Diary/Edit/5

        [HttpPost]
        public ActionResult Edit(DailyEntry dailyentry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dailyentry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dailyentry);
        }

        //
        // GET: /Diary/Delete/5

        public ActionResult Delete(int id = 0)
        {
            DailyEntry dailyentry = db.RunDiary.Find(id);
            if (dailyentry == null)
            {
                return HttpNotFound();
            }
            return View(dailyentry);
        }

        //
        // POST: /Diary/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DailyEntry dailyentry = db.RunDiary.Find(id);
            db.RunDiary.Remove(dailyentry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult SearchFunc(string searchString)
        {
            var result = from d in db.RunDiary
                         select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                result = result.Where(s => s.My_Run.Contains(searchString));
            }

            return View(result);
        }
    }
}

RunnerDiary/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RunnerDiary.Models;

namespace RunnerDiary.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Keep Track of Your Running Workout";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        [HttpGet]
        public ActionResult ContactUs()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ContactUs");
            }

            return View();
        }

        [HttpPost]
        public ActionResult ContactUs(ContactUsInput input)
        {
            if (!ModelState.IsValid)
            {
                if (Request.IsAjaxRequest())
                    return PartialView("_ContactUs", input);

                return View(input);
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ThanksForFeedback", input);
            }

            TempData["Message"] = string.Format("Thanks for the feedback, {0}! We will contact you shortly.", input.Name);
            return RedirectToAction("Index");
        }
    }
}

RunnerDiary/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

RunnerDiary/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

RunnerDiary/Views/Home/ContactUs.cshtml
@model RunnerDiary.Models.ContactUsInput

<h2>Contact Us</h2>

@Html.Partial("_ContactUs")

RunnerDiary/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Message</h1>
            </hgroup>            
        </div>
    </section>
}

<script type="text/javascript">
    $.ajaxSetup({ cache: false });

    $(document).ready(function () {
        $(".openDialog").live("click", function (e) {
            e.preventDefault();

            $("<div></div>")
                .addClass("dialog")
                .attr("id", $(this).attr("data-dialog-id"))
                .appendTo("body")
                .dialog({
                    title: $(this).attr("data-dialog-title"),
                    close: function () { $(this).remove() },
                    modal: true
                })
                .load(this.href);
        });

        $(".close").live("click", function (e) {
            e.preventDefault();
            $(this).closest(".dialog").dialog("close");
        });
    });
</script>

<ol class="round">
    <li class="one">
        <h5>Get Active, Get Motivated, Get Running</h5>
        Bruce Lee once said that running was the king of exercise.  The benefits of the
        workout was evident in his explosive speed, amazing agility and his martial art
        prowess.  That is not all.  Every military branch uses running as one of the factors
        to gauge the servicemember's physical fitness.  So if your goal is to dive deep into
        the sea with the famous Navy SEALs or roll around the desert in an almighty M1A2 Abrams tank,
        the first thing to prepare for it is be the best runner you can be.
        <a href="http://ririanproject.com/2007/10/22/10-benefits-of-running-and-how-to-do-it/">Find out more about benefits of running…</a>
    </li>

    <li class="two">
        <h5>Be The Best You Can Be, One Workout At A Time</h5>
        Whether it's Great Wall of China, or three pyramids in King's Valley Egypt, they all
        started taking shape one brick at a time.  So start building your running pyramid with
        an everyday running workout.
        <a href="http://www.runnersworld.com/beginners/8-week-beginners-program?page=single">Learn more…</a>
    </li>

    <li class="three">
        <h5>Use The Diary to Keep Your Eyes On The Prize</h5>
        This App is made to help you keep track of your daily running goal.  It allows you to
        put in your exercise goal before your daily workout, and write down your distance after
        your running workout.
        <a>@Html.ActionLink("Write Your Running Diary", "Index", "Diary")</a>
    </li>
</ol>

@Html.ActionLink("Contact Us", "ContactUs", "Home", null, new{ @class = "openDialog", data_dialog_id = "emailDialog", data_dialog_title = "Contact Us"})

RunnerDiary/Views/Home/_ContactUs.cshtml
@model RunnerDiary.Models.ContactUsInput

@using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "emailDialog" }))
{
    @Html.ValidationSummary(true)
    @Html.EditorForModel()

    <p>
        <input type="submit" value="Send Message" />
    </p>
}

RunnerDiary/Views/Home/_ThanksForFeedback.cshtml
@model RunnerDiary.Models.ContactUsInput

<p>Thank you for your feedback, @Model.Name!  We  will contact you shortly.</p>
<p><a href="javascript:void(0);" class="close">Close Window</a></p>